### ISSUE TITLE
Generic Docker usage tutorial

### ISSUE THREAD

**Issue by kwhinnery** [denoland/docs#160] opened 2023-10-09 17:14 UTC
In the core docs, we should include a more robust Docker example. It could be a slightly more beefed up version of what appears in the Fresh docs here:

https://fresh.deno.dev/docs/concepts/deployment

**Comment by thisisjofrank** [comment] 2024-12-06 16:26
Closing as duplicate of https://github.com/denoland/docs/issues/1157

**Closed by thisisjofrank** 2024-12-06 16:26 UTC
